repos:
-   repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
    - id: black
      language_version: python3
      exclude: micone/pipelines/templates
-   repo: https://github.com/sourcery-ai/sourcery
    rev: v1.8.0
    hooks:
      - id: sourcery
        # The best way to use Sourcery in a pre-commit hook:
        # * review only changed lines:
        # * omit the summary
        args: [--diff=git diff HEAD, --no-summary]
