# Config file for automatic testing at travis-ci.org

language: python
python: 3.6

# Command to install dependencies, e.g. pip install r requirements.txt usemirrors
install:
    - pip install -r requirements.txt
    - pip install -r requirements_dev.txt
    - pip install .

# Command to run tests, e.g. python setup.py test
script:
    - pytest -sv --cov=mindpipe
    - flake8 mindpipe
    - travis-sphinx build --source=docs --nowarn

after_success:
    - travis-sphinx deploy
