################################################################################
# external pipelines
################################################################################

[qiime1.demultiplexing.454]
  env = "src/external/qiime1/env"
  root = "src/external/qiime1/demultiplexing/454"
  output_location = "qiime1/demultiplexing"
  [[qiime1.demultiplexing.454.input]]
    datatype = "sequence_16s"
    format = ["fastq", "fasta"]  # QUESTION: shouldn't this be sff?
  [[qiime1.demultiplexing.454.input]]
    datatype = "quality"
    format = ["qual"]
  [[qiime1.demultiplexing.454.input]]
    datatype = "mapping"
    format = ["tsv", "txt"]
  [[qiime1.demultiplexing.454.process]]
    process = "demultiplexing_fasta"
    qual_score_window = 50
  [[qiime1.demultiplexing.454.output]]
    datatype = "sequence_16s"
    format = ["fasta"]
    location = "seqs/*.fna"

[qiime1.demultiplexing.illumina]

[qiime1.denovo_picking]

[qiime1.closedref_picking]

[qiime1.openref_picking]

[qiime2.sequence_importer]

[qiime2.demultiplexing]

[qiime2.dada2]

[qiime2.deblur]

[qiime2.taxonomy]

[qiime2.export]

[format_converters.sequence_16s]

[format_converters.otu_table]

[format_converters.sff2fasta]

