################################################################################
# external pipelines
################################################################################

[qiime1.demultiplexing.454]
  env = "src/external/qiime1/env"
  root = "src/external/qiime1/demultiplexing/454"
  output_location = "qiime1/demultiplexing"
  [[qiime1.demultiplexing.454.input]]
    datatype = "sequence_16s"
    format = ["fastq", "fasta"]  # QUESTION: shouldn't this be sff?
  [[qiime1.demultiplexing.454.input]]
    datatype = "quality"
    format = ["qual"]
  [[qiime1.demultiplexing.454.input]]
    datatype = "mapping"
    format = ["tsv", "txt"]
  [[qiime1.demultiplexing.454.process]]
    process = "demultiplexing_fasta"
    qual_score_window = 50
  [[qiime1.demultiplexing.454.output]]
    datatype = "sequence_16s"
    format = ["fasta"]
    location = "seqs/*.fna"

[qiime1.demultiplexing.illumina]
  env = "src/external/qiime1/env"
  root = "src/external/qiime1/demultiplexing/illumina"
  output_location = "qiime1/demultiplexing"
  [[qiime1.demultiplexing.illumina.input]]
    datatype = "sequence_16s"
    format = ["fastq", "fasta"]
  [[qiime1.demultiplexing.illumina.input]]
    datatype = "barcode"
    format = ["fastq"]
  [[qiime1.demultiplexing.illumina.input]]
    datatype = "qiime2_mapping"
    format = ["tsv", "txt"]
  [[qiime1.demultiplexing.illumina.process]]
    process =  "demultiplexing_fastq"
    phred_quality_threshold = 3
  [[qiime1.demultiplexing.illumina.output]]
    datatype = "sequence_16s"
    format = ["fasta"]
    location  = "seqs/*.fna"

[qiime1.clustering.denovo]
  env = "src/external/qiime1/env"
  root = "src/external/qiime1/clustering/denovo"
  output_location = "qiime1/clustering"
  [[qiime1.clustering.denovo.input]]
    datatype = "sequence_16s"
    format = ["fasta"]
  [[qiime1.clustering.denovo.input]]
    datatype = "qiime1_parameters"
    format = ["txt"]
  [[qiime1.clustering.denovo.process]]
    process = "pick_de_novo_otus"
    ncpus = 4
  [[qiime1.clustering.denovo.output]]
    datatype = "otu_table"
    format = ["biom"]
    location = "otu_table.biom"
  [[qiime1.clustering.denovo.output]]
    datatype = "phylogenetic_tree"
    format = ["tre"]
    location = "rep_set.tre"
  [[qiime1.clustering.denovo.output]]
    datatype = "sequence_16s"
    format = ["fasta"]
    location = "rep_seqs.{fasta,fna}"

[qiime1.clustering.closedref]
  env = "src/external/qiime1/env"
  root = "src/external/qiime1/clustering/closedref"
  output_location = "qiime1/clustering"
  [[qiime1.clustering.closedref.input]]
    datatype = "sequence_16s"
    format = ["fasta"]
  [[qiime1.clustering.closedref.input]]
    datatype = "sequence_16s_reference"
    format = ["fasta"]
    location = "src/external/qiime1/env/lib/python2.7/site-packages/qiime_default_reference/gg_13_8_otus/rep_set/97_otus.fasta"
  [[qiime1.clustering.closedref.input]]
    datatype = "sequence_taxonomy_mapping"
    format = ["txt"]
    location = "src/external/qiime1/env/lib/python2.7/site-packages/qiime_default_reference/gg_13_8_otus/taxonomy/97_otu_taxonomy.txt"
  [[qiime1.clustering.closedref.input]]
    datatype = "qiime1_parameters"
    format = ["txt"]
  [[qiime1.clustering.closedref.process]]
    process = "pick_closed_reference_otus"
    ncpus = 4
  [[qiime1.clustering.closedref.output]]
    datatype = "otu_table"
    format = ["biom"]
    location = "otu_table.biom"
  [[qiime1.clustering.closedref.output]]
    datatype = "phylogenetic_tree"
    format = ["tre"]
    location = "rep_set.tre"

[qiime1.openref_picking]

[qiime2.sequence_importer]

[qiime2.demultiplexing]

[qiime2.dada2]

[qiime2.deblur]

[qiime2.taxonomy]

[qiime2.export]

[format_converters.sequence_16s]

[format_converters.otu_table]

[format_converters.sff2fasta]

