################################################################################
# internal pipelines
################################################################################

[split_otu_table]
  root = "src/internal/split_otu_table"
  output_location = "split_otu_table"
  [[split_otu_table.input]]
    datatype = "otu_table"
    format = ["biom"]
  [[split_otu_table.output]]
    datatype = "otu_table"
    format = ["biom"]

[normalize_otu_table]
  root = "src/internal/normalize_otu_table"
  output_location = "normalize_otu_table"
  [[normalize_otu_table.input]]
    datatype = "otu_table"
    format = ["biom"]
  [[normalize_otu_table.output]]
    datatype = "otu_table"
    format = ["biom"]

[group_by_taxa]
  root = "src/internal/group_by_taxa"
  output_location = "group_by_taxa"
  [[group_by_taxa.input]]
    datatype = "otu_table"
    format = ["biom"]
  [[group_by_taxa.process]]
    process = "group_by_taxa"
    rm_sparse_otu = "True"
    rm_sparse_samples = "True"
    tax_levels = "['phylum', 'class', 'order', 'family', 'genus', 'species']"
  [[group_by_taxa.output]]
    datatype = "otu_table"
    format = ["biom"]
    location = "group_by_taxa/**/*.biom"
  [[group_by_taxa.output]]
    datatype = "children_object"
    format = ["json"]
    location = "group_by_taxa/**/*_children.json"

[make_json_network]

[helpers.clean]

[helpers.process_verifier]

[helpers.drop_lineage_fromotu]
