################################################################################
# internal pipelines
# NOTE: For consistency we need all entries to be mono-level
################################################################################

[split_otu_table]
  root = "src/internal/split_otu_table"
  output_location = "split_otu_table"
  [[split_otu_table.input]]
    datatype = "otu_table"
    format = ["biom"]
  [[split_otu_table.output]]
    datatype = "otu_table"
    format = ["biom"]

[normalize_otu_table]
  root = "src/internal/normalize_otu_table"
  output_location = "normalize_otu_table"
  [[normalize_otu_table.input]]
    datatype = "otu_table"
    format = ["biom"]
  [[normalize_otu_table.output]]
    datatype = "otu_table"
    format = ["biom"]

[group_by_taxa]
  root = "src/internal/group_by_taxa"
  output_location = "group_by_taxa"
  [[group_by_taxa.input]]
    datatype = "otu_table"
    format = ["biom"]
  [[group_by_taxa.process]]
    process = "group_by_taxa"
    rm_sparse_otu = "True"
    rm_sparse_samples = "True"
    tax_levels = "['phylum', 'class', 'order', 'family', 'genus', 'species']"
  [[group_by_taxa.output]]
    datatype = "otu_table"
    format = ["biom"]
    location = "group_by_taxa/**/*.biom"
  [[group_by_taxa.output]]
    datatype = "children_object"
    format = ["json"]
    location = "group_by_taxa/**/*_children.json"

[make_json_network]
  root = "src/internal/make_json_network"
  output_location = "make_json_network"
  [[make_json_network.input]]
    datatype = "interaction_table"
    format = ["tsv"]
  [[make_json_network.input]]
    datatype = "pvalue_table"
    format = ["tsv"]
  [[make_json_network.input]]
    datatype = "observation_metadata"
    format = ["csv"]
  [[make_json_network.input]]
    datatype = "children_map"
    format = ["json"]
  [[make_json_network.input]]
    datatype = "computational_metadata"
    format = ["json"]
  [[make_json_network.input]]
    datatype = "metadata"
    format = ["json"]
  [[make_json_network.process]]
    process = "make_jsonnet"
  [[make_json_network.output]]
    datatype = "network"
    format = ["json"]
    location = "make_jsonnet/**/*_net.json"

[drop_lineage_fromotu]
  root = "src/internal/drop_lineage_fromotu"
  output_location = "drop_lineage_fromotu"
  [[drop_lineage_fromotu.input]]
    datatype = "otu_table"
    format = ["tsv"]
  [[drop_lineage_fromotu.process]]
    process = "drop_lineage"
  [[drop_lineage_fromotu.process]]
    process = "make_lineage"
  [[drop_lineage_fromotu.process]]
    processs = "make_sample_metadata"
  [[drop_lineage_fromotu.output]]
    datatype = "otu_table"
    format = ["tsv"]
    location = "drop_lineage_fromotu/*_otu.tsv"
  [[drop_lineage_fromotu.output]]
    datatype = "observation_metadata"
    format = ["csv"]
    location = "drop_lineage_fromotu/*_taxondata.csv"
  [[drop_lineage_fromotu.output]]
    datatype = "sample_metadata"
    format = ["csv"]
    location = "drop_lineage_fromotu/*_sample_metadata.csv"
