################################################################################
# internal pipelines
# NOTE: For consistency we need all entries to be mono-level
################################################################################

[split_otu_table]
  root = "src/internal/split_otu_table"
  output_location = "split_otu_table"
  [[split_otu_table.input]]
    datatype = "otu_table"
    format = ["biom"]
  [[split_otu_table.parameters]]
    process = ""
  [[split_otu_table.output]]
    datatype = "otu_table"
    format = ["biom"]
    location = "split_otu_table/*.biom"

[normalize_otu_table]
  root = "src/internal/normalize_otu_table"
  output_location = "normalize_otu_table"
  [[normalize_otu_table.input]]
    datatype = "otu_table"
    format = ["biom"]
  [[normalize_otu_table.parameters]]
    process = "normalize_otu_table"
    axis = "sample"
    count_thres = 500
    prevalence_thres = 0.05
    abundance_thres = 0.01
    rm_sparse_obs = "True"
    rm_sparse_samples = "True"
  [[normalize_otu_table.output]]
    datatype = "otu_table"
    format = ["biom"]
    location = "normalize_otu_table/*.biom"

[group_by_taxa]
  root = "src/internal/group_by_taxa"
  output_location = "group_by_taxa"
  [[group_by_taxa.input]]
    datatype = "otu_table"
    format = ["biom"]
  [[group_by_taxa.parameters]]
    process = "group_by_taxa"
    tax_levels = "['Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species']"
  [[group_by_taxa.output]]
    datatype = "otu_table"
    format = ["biom"]
    location = "group_by_taxa/**/*.biom"
  [[group_by_taxa.output]]
    datatype = "children_map"
    format = ["json"]
    location = "group_by_taxa/**/*_children.json"

[make_json_network]
  root = "src/internal/make_json_network"
  output_location = "make_json_network"
  [[make_json_network.input]]
    datatype = "interaction_table"
    format = ["tsv"]
  [[make_json_network.input]]
    datatype = "pvalue_table"
    format = ["tsv"]
  [[make_json_network.input]]
    datatype = "observation_metadata"
    format = ["csv"]
  [[make_json_network.input]]
    datatype = "children_map"
    format = ["json"]
  [[make_json_network.input]]
    datatype = "computational_metadata"
    format = ["json"]
  [[make_json_network.input]]
    datatype = "metadata"
    format = ["json"]
  [[make_json_network.parameters]]
    process = "make_jsonnet"
  [[make_json_network.output]]
    datatype = "network"
    format = ["json"]
    location = "make_jsonnet/**/*_net.json"

[export_biom]
  root = "src/internal/export_biom"
  output_location = "export_biom"
  [[export_biom.input]]
    datatype = "otu_table"
    format = ["biom"]
  [[export_biom.output]]
    datatype = "otu_table"
    format = ["tsv"]
    location = "export_biom/*_otu.tsv"
  [[export_biom.output]]
    datatype = "observation_metadata"
    format = ["csv"]
    location = "export_biom/*_obs_metadata.csv"
  [[export_biom.output]]
    datatype = "sample_metadata"
    format = ["csv"]
    location = "export_biom/*_sample_metadata.tsv"
  [[export_biom.parameters]]
    process = "export_biom"
