# Pipelines for the otu_processing module

## filter

[otu_processing.filter.abundance]
  env = "mindpipe"
  output_location = "filter/abundance"
  [[otu_processing.filter.abundance.input]]
    datatype = "otu_table"
    format = ["biom"]
  [[otu_processing.filter.abundance.parameters]]
    process = "filter"
    count_thres = 500
    prevalence_thres = 0.05
    abundance_thres = 0.01
  [[otu_processing.filter.abundance.output]]
    datatype = "otu_table"
    format = ["biom"]
    location = "filter/abundance/**/*_filtered.biom"

[otu_processing.filter.group]
  env = "mindpipe"
  output_location = "filter/group"
  [[otu_processing.filter.group.input]]
    datatype = "otu_table"
    format = ["biom"]
  [[otu_processing.filter.group.parameters]]
    process = "group"
    tax_levels = "['Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species']"
  [[otu_processing.filter.group.output]]
    datatype = "otu_table"
    format = ["biom"]
    location = "filter/group/**/*.biom"
  [[otu_processing.filter.group.output]]
    datatype = "children_map"
    format = ["json"]
    location = "filter/group/**/*_children.json"

[otu_processing.filter.partition]
  env = "mindpipe"
  output_location = "filter/partition"
  [[otu_processing.filter.partition.input]]
    datatype = "otu_table"
    format = ["biom"]
  [[otu_processing.filter.partition.parameters]]
    process = ""
  [[otu_processing.filter.partition.output]]
    datatype = "otu_table"
    format = ["biom"]
    location = "filter/partition/**/*.biom"


## Transform

[otu_processing.transform.normalize]
  env = "mindpipe"
  output_location = "transform/normalize"
  [[otu_processing.transform.normalize.input]]
    datatype = "otu_table"
    format = ["biom"]
  [[otu_processing.transform.normalize.parameters]]
    process = "normalize"
    axis = "sample"
    count_thres = 500
    prevalence_thres = 0.05
    abundance_thres = 0.01
    rm_sparse_obs = "True"
    rm_sparse_samples = "True"
  [[otu_processing.transform.normalize.output]]
    datatype = "otu_table"
    format = ["biom"]
    location = "*.biom"


## Export

[otu_processing.export.biom2tsv]
  env = "mindpipe"
  output_location = "export/biom2tsv"
  [[otu_processing.export.biom2tsv.input]]
    datatype = "otu_table"
    format = ["biom"]
  [[otu_processing.export.biom2tsv.output]]
    datatype = "otu_table"
    format = ["tsv"]
    location = "biom2tsv/*_otu.tsv"
  [[otu_processing.export.biom2tsv.output]]
    datatype = "observation_metadata"
    format = ["csv"]
    location = "biom2tsv/*_obs_metadata.csv"
  [[otu_processing.export.biom2tsv.output]]
    datatype = "sample_metadata"
    format = ["csv"]
    location = "biom2tsv/*_sample_metadata.tsv"
  [[otu_processing.export.biom2tsv.parameters]]
    process = "biom2tsv"
