# Pipelines for the otu_assignment module

## Sequence processing

[otu_assignment.sequence_processing.join_reads]
  env = "mindpipe-qiime1"
  output_location = "joined_reads"
  [[otu_assignment.sequence_processing.join_reads.input]]
    datatype = "sequence_16s"
    format = ["fastq", "fastq.gz"]
  [[otu_assignment.sequence_processing.join_reads.input]]
    datatype = "barcode"
    format = ["fastq", "fastq.gz"]
  [[otu_assignment.sequence_processing.join_reads.parameters]]
    process = "join_reads"
    min_overlap = 6
    perc_max_diff = 8
  [[otu_assignment.sequence_processing.join_reads.output]]
    datatype = "sequence_16s"
    format = ["fastq.gz"]
    location = "joined_reads/**/*_reads.fastq.gz"
  [[otu_assignment.sequence_processing.join_reads.output]]
    datatype = "barcode"
    format = ["fastq.gz"]
    location = "joined_reads/**/*_barcodes.fastq.gz"

# [otu_assignment.sequence_processing.join_reads_demux]

[otu_assignment.sequence_processing.demultiplex_illumina]
  env = "mindpipe-qiime2"
  output_location = "demultiplex"
  [[otu_assignment.sequence_processing.demultiplex_illumina.input]]
    datatype = "sequence_16s"
    format = ["fastq", "fastq.gz"]
  [[otu_assignment.sequence_processing.demultiplex_illumina.input]]
    datatype = "barcode"
    format = ["fastq", "fastq.gz"]
  [[otu_assignment.sequence_processing.demultiplex_illumina.input]]
    datatype = "sample_barcode_mapping"
    format = ["tsv", "txt"]
  [[otu_assignment.sequence_processing.demultiplex_illumina.parameters]]
    process = "demultiplex"
    rev_comp_barcodes = "False"
    rev_comp_mapping_barcodes = "False"
  [[otu_assignment.sequence_processing.demultiplex_illumina.output]]
    datatype = "sequence_16s"
    format = ["fastq.gz"]
    location = "demultiplex/**/*.fastq.gz"
  [[otu_assignment.sequence_processing.demultiplex_illumina.output]]
    datatype = "sample_sequence_manifest"
    format = [""]
    location = "demultiplex/**/MANIFEST"

[otu_assignment.sequence_processing.demultiplexing_454]
  env = "mindpipe-qiime1"
  output_location = "demultiplexing"
  [[otu_assignment.sequence_processing.demultiplexing_454.input]]
    datatype = "sequence_16s"
    format = ["fasta"]
  [[otu_assignment.sequence_processing.demultiplexing_454.input]]
    datatype = "quality"
    format = ["qual"]
  [[otu_assignment.sequence_processing.demultiplexing_454.input]]
    datatype = "sample_barcode_mapping"
    format = ["tsv", "txt"]
  [[otu_assignment.sequence_processing.demultiplexing_454.output]]
    datatype = "sequence_16s"
    format = ["fasta"]
    location = "seqs/*.fna"
  [[otu_assignment.sequence_processing.demultiplexing_454.parameters]]
    process = "demultiplexing"

# [otu_assignment.sequence_processing.trim_filter_auto]

[otu_assignment.sequence_processing.trim_filter_fixed]
  env = "mindpipe-qiime2"
  output_location = "trimmed"
  [[otu_assignment.sequence_processing.trim_filter_fixed.input]]
    datatype = "sequence_16s"
    format = ["fastq.gz"]
  [[otu_assignment.sequence_processing.trim_filter_fixed.input]]
    datatype = "sample_sequence_manifest"
    format = [""]
  [[otu_assignment.sequence_processing.trim_filter_fixed.parameters]]
    process = "export_visualization"
    seq_samplesize = 10000
  [[otu_assignment.sequence_processing.trim_filter_fixed.parameters]]
    process = "trimming"
    ncpus = 2
    max_ee = 2
    trunc_q = 2
  [[otu_assignment.sequence_processing.trim_filter_fixed.output]]
    datatype = "sequence_16s"
    format = ["fastq.gz"]
    location = "trimmed/**/*.fastq.gz"
  [[otu_assignment.sequence_processing.trim_filter_fixed.output]]
    datatype = "sample_sequence_manifest"
    format = [""]
    location = "trimmed/**/MANIFEST"

[otu_assignment.sequence_processing.chimera_checking]
  env = "mindpipe-qiime2"
  output_location = "chimera_checking"
  [[otu_assignment.sequence_processing.chimera_checking.input]]
    datatype = "sequence_16s_representative"
    format = ["fasta"]
  [[otu_assignment.sequence_processing.chimera_checking.input]]
    datatype = "otu_table"
    format = ["biom"]
  [[otu_assignment.sequence_processing.chimera_checking.output]]
    datatype = "sequence_16s_representative"
    format = ["fasta"]
    location = "*_nonchimeric.fasta"
  [[otu_assignment.sequence_processing.chimera_checking.output]]
    datatype = "otu_table"
    format = ["biom"]
    location = "*_nonchimeric.biom"
  [[otu_assignment.sequence_processing.chimera_checking.parameters]]
    process = "chimera_checking"


## Denosing and clustering

[otu_assignment.denoise_cluster.de_novo]
  env = "mindpipe-qiime1"
  output_location = "de_novo"
  [[otu_assignment.denoise_cluster.de_novo.input]]
    datatype = "sequence_16s"
    format = ["fastq.gz", "fastq"]
  [[otu_assignment.denoise_cluster.de_novo.input]]
    datatype = "sample_sequence_manifest"
    format = [""]
  [[otu_assignment.denoise_cluster.de_novo.parameters]]
    process = "pick_de_novo_otus"
    parameters = "${PIPELINE_DIR}/otu_assignment/denoise_cluster/qiime1_parameters.txt"
    ncpus = 1
  [[otu_assignment.denoise_cluster.de_novo.output]]
    datatype = "otu_table"
    format = ["biom"]
    location = "de_novo/**/otu_table.biom"
  [[otu_assignment.denoise_cluster.de_novo.output]]
    datatype = "sequence_16s_representative"
    format = ["fasta"]
    location = "de_novo/**/rep_seqs.fasta"

[otu_assignment.denoise_cluster.closed_reference]
  env = "mindpipe-qiime1"
  output_location = "closed_reference"
  [[otu_assignment.denoise_cluster.closed_reference.input]]
    datatype = "sequence_16s"
    format = ["fastq.gz", "fastq"]
  [[otu_assignment.denoise_cluster.closed_reference.input]]
    datatype = "sample_sequence_manifest"
    format = [""]
  [[otu_assignment.denoise_cluster.closed_reference.input]]
    datatype = "sequence_16s_reference"
    format = ["fasta"]
    location = "${CONDA_PREFIX}/lib/python2.7/site-packages/qiime_default_reference/gg_13_8_otus/rep_set/97_otus.fasta"
  [[otu_assignment.denoise_cluster.closed_reference.parameters]]
    process = "pick_closed_reference_otus"
    ncpus = 1
    parameters = "${PIPELINE_DIR}/otu_assignment/denoise_cluster/qiime1_parameters.txt"
  [[otu_assignment.denoise_cluster.closed_reference.output]]
    datatype = "otu_table"
    format = ["biom"]
    location = "closed_reference/**/otu_table.biom"
  [[otu_assignment.denoise_cluster.closed_reference.output]]
    datatype = "sequence_16s_representative"
    format = ["fasta"]
    location = "closed_reference/**/rep_seqs.fasta"

[otu_assignment.denoise_cluster.open_reference]
  env = "mindpipe-qiime1"
  output_location = "open_reference"
  [[otu_assignment.denoise_cluster.open_reference.input]]
    datatype = "sequence_16s"
    format = ["fastq.gz", "fastq"]
  [[otu_assignment.denoise_cluster.open_reference.input]]
    datatype = "sample_sequence_manifest"
    format = [""]
  [[otu_assignment.denoise_cluster.open_reference.input]]
    datatype = "sequence_16s_reference"
    format = ["fasta"]
    location = "${CONDA_PREFIX}/lib/python2.7/site-packages/qiime_default_reference/gg_13_8_otus/rep_set/97_otus.fasta"
  [[otu_assignment.denoise_cluster.open_reference.parameters]]
    process = "pick_open_reference_otus"
    ncpus = 1
    parameters = "${PIPELINE_DIR}/otu_assignment/denoise_cluster/qiime1_parameters.txt"
    picking_method = "sortmerna_sumaclust"
  [[otu_assignment.denoise_cluster.open_reference.output]]
    datatype = "otu_table"
    format = ["biom"]
    location = "open_reference/**/otu_table.biom"
  [[otu_assignment.denoise_cluster.open_reference.output]]
    datatype = "sequence_16s_representative"
    format = ["fasta"]
    location = "open_reference/**/rep_seqs.fasta"

[otu_assignment.denoise_cluster.dada2]
  env = "mindpipe-dada2"
  output_location = "dada2"
  [[otu_assignment.denoise_cluster.dada2.input]]
    datatype = "sequence_16s"
    format = ["fastq.gz", "fastq"]
  [[otu_assignment.denoise_cluster.dada2.input]]
    datatype = "sample_sequence_manifest"
    format = [""]
  [[otu_assignment.denoise_cluster.dada2.parameters]]
    process = "dada2"
    ncpus = 1
    big_data = "FALSE"
  [[otu_assignment.denoise_cluster.dada2.output]]
    datatype = "otu_table"
    format = ["biom"]
    location = "dada2/**/otu_table.biom"
  [[otu_assignment.denoise_cluster.dada2.output]]
    datatype = "sequence_16s_representative"
    format = ["fasta"]
    location = "dada2/**/rep_seqs.fasta"

[otu_assignment.denoise_cluster.deblur]
  env = "mindpipe-qiime2"
  output_location = "deblur"
  [[otu_assignment.denoise_cluster.deblur.input]]
    datatype = "sequence_16s"
    format = ["fastq.gz", "fastq"]
  [[otu_assignment.denoise_cluster.deblur.input]]
    datatype = "sample_sequence_manifest"
    format = [""]
  [[otu_assignment.denoise_cluster.deblur.parameters]]
    process = "deblur"
    ncpus = 1
    min_reads = 2
    min_size = 2
  [[otu_assignment.denoise_cluster.deblur.output]]
    datatype = "otu_table"
    format = ["biom"]
    location = "deblur/**/otu_table.biom"
  [[otu_assignment.denoise_cluster.deblur.output]]
    datatype = "sequence_16s_representative"
    format = ["fasta"]
    location = "deblur/**/rep_seqs.fasta"
